version: "3.9"
services:
  price_feed:
    container_name: price_feed
    build:
      context: .
      target: production
    image: price_feed
    restart: always
    command: "tini -- /bin/price_feed"
    logging:
      driver: json-file
      options:
        max-size: "15m"
        max-file: "3"
    environment:
      ENV: prod
      DEBUG: no
      MIGRATION: no
    env_file:
      - .env
