version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: my-postgres-container
    restart: always
    environment:
      POSTGRES_USER: sui_indexer
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data